### ISSUE TITLE
US 01.01/03/04.01 [NEW] - Habit public option

### ISSUE THREAD

**Issue by jboileau99** [CMPUT301F21T31/Habit#93]
Statement: As a doer, I want to add a habit, giving it a brief title, reason, date to start, and _**whether it is public or private**_

Risk: High
Priority: Medium
Story points: 5
Additional Requirement (Added after original list): Yes

**General Requirements**
- [x] Implemented
- [x] Tested
- [ ] Integrated
- [ ] Documented (Javadoc style in code)

**Subtasks**
- [x] Add public boolean to habit class and update parcel methods
- [x] Add something to habit add/edit/view UI to choose and display the public/private option
- [ ] Update figma with UI changes
